FROM node:10.16.3-alpine

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json

RUN npm install --prefix /usr/lib/node_modules/

COPY . /usr/src/app

RUN npm install

EXPOSE 8080

CMD ["npm", "run", "dev"]
#ENTRYPOINT ["/bin/sh", "-c", "while true; do sleep 1; done"]
